### PR TITLE
Feature/266 rdfa parser fix according to w3c tests results

### LINKED ISSUE #266: RDFa parser fix according to W3C tests results

### PR DESCRIPTION
**Pull request by abdessamad-abdoun**

### CODE REVIEW

File: src/main/java/fr/inria/corese/core/next/data/impl/io/parser/rdfa/RDFaParser.java [hunk 1]
```diff
@@ -741,7 +844,36 @@ protected Optional<Resource> resolveStringResource(String stringResource) {
...
+            return false;
+        }
+
+        if (stringIri.contains("://")) {
+            return false;
+        }
+
+        String potentialScheme = stringIri.substring(0, colonIndex).toLowerCase();
+
+        return !potentialScheme.equals("http") &&
```
Comment (MaillPierre) [inline src/main/java/fr/inria/corese/core/next/data/impl/io/parser/rdfa/RDFaParser.java]: Any protocol should be accepted; do not hard-code protocols here, please

**Review by MaillPierre — CHANGES_REQUESTED** [review]

**Review by MaillPierre — APPROVED** [review]

File: src/main/java/fr/inria/corese/core/next/data/impl/io/parser/rdfa/model/RDFaIncompleteStatement.java [hunk 2]
```diff
@@ -3,6 +3,7 @@
 import fr.inria.corese.core.next.data.api.IRI;
 import fr.inria.corese.core.next.data.api.Resource;
 import fr.inria.corese.core.next.data.api.Value;
+import java.util.Objects;
```
Comment (remiceres) [inline src/main/java/fr/inria/corese/core/next/data/impl/io/parser/rdfa/model/RDFaIncompleteStatement.java]: The import java.util.Objects is never used

**Review by remiceres — APPROVED** [review]

**Review by remiceres — APPROVED** [review]
