### PR TITLE
248 Fix: Allow for the usage of objects inheriting IOOptions as config of  all serializers

### LINKED ISSUE #248: Fix: Allow for the usage of objects inheriting IOOptions as config of  all serializers
Linked to #247

### PR DESCRIPTION
**Pull request by MaillPierre**

### CODE REVIEW

File: src/main/java/fr/inria/corese/core/next/impl/common/util/IRIUtils.java [hunk 1]
```diff
@@ -1,5 +1,8 @@
 package fr.inria.corese.core.next.impl.common.util;
 
+import org.slf4j.Logger;
```
Comment (remiceres) [inline src/main/java/fr/inria/corese/core/next/impl/common/util/IRIUtils.java]: The imports are never usedJava

File: src/main/java/fr/inria/corese/core/next/impl/io/serialization/rdfxml/RDFXMLSerializer.java [hunk 2]
```diff
@@ -4,18 +4,14 @@
...
 import java.util.stream.Collectors;
 
 import fr.inria.corese.core.next.api.base.io.RDFFormat;
+import fr.inria.corese.core.next.api.io.IOOptions;
+import fr.inria.corese.core.next.api.io.serializer.*;
+import fr.inria.corese.core.next.impl.common.prefix.PrefixHandler;
+import fr.inria.corese.core.next.impl.common.util.IRIUtils;
 import fr.inria.corese.core.next.impl.common.vocabulary.*;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
```
Comment (remiceres) [inline src/main/java/fr/inria/corese/core/next/impl/io/serialization/rdfxml/RDFXMLSerializer.java]: The imports are never usedJava

File: src/main/java/fr/inria/corese/core/next/impl/io/serialization/rdfxml/RDFXMLSerializer.java [hunk 3]
```diff
@@ -302,7 +282,7 @@ private void addPrefixMapping(String namespaceURI, String prefix) {
     private String generateUniquePrefix(String basePrefix) {
```
Comment (remiceres) [inline src/main/java/fr/inria/corese/core/next/impl/io/serialization/rdfxml/RDFXMLSerializer.java]: unused method

File: src/main/java/fr/inria/corese/core/next/impl/io/serialization/SerializerFactory.java [hunk 4]
```diff
@@ -16,7 +16,7 @@
 import fr.inria.corese.core.next.impl.io.serialization.ntriples.NTriplesSerializer;
 import fr.inria.corese.core.next.impl.io.serialization.ntriples.NTriplesSerializerOptions;
 import fr.inria.corese.core.next.impl.io.serialization.rdfxml.RDFXMLSerializer;
-import fr.inria.corese.core.next.impl.io.serialization.rdfxml.RDFXMLSerializerOption;
+import fr.inria.corese.core.next.impl.io.serialization.rdfxml.RDFXMLSerializerOptions;
```
Comment (remiceres) [inline src/main/java/fr/inria/corese/core/next/impl/io/serialization/SerializerFactory.java]: Imports are never used

**Review by remiceres — APPROVED** [review]

**Review by abdessamad-abdoun — APPROVED** [review]
